// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Prisma CLI (migrate/introspect) needs Neon's direct, unpooled connection.
    // Runtime queries use the pooled DATABASE_URL via the adapter in lib/db.ts instead.
    url: process.env["DIRECT_URL"],
  },
});
